name: Laserdome
version: '${project.version}'
main: io.github.cardsandhuskers.laserdome.Laserdome
api-version: 1.21
authors: [ cardsandhuskers ]
description: Bow duels basically
softdepend: [Multiverse-Core, PlaceholderAPI]
commands:
  startLaserdome:
    description: starts the game
    usage: /<command>
  setLaserdomeLobby:
    description: sets lobby location
    usage: /<command>
  setLaserdomeTeamSpawn:
    description: set team spawn
    usage: /<command> [A or B]
  setLaserdomeSpecSpawn:
    description: sets the spawn point for the spectators
    usage: /<command>
  setLaserdomePos1:
    description: sets corner 1 of the whole area
    usage: /<command>
  setLaserdomePos2:
    description: sets corner 2 of the whole area
    usage: /<command>
  setLaserdomeArenaLoc1:
    description: sets corner 1 of the arena
    usage: /<command>
  setLaserdomeArenaLoc2:
    description: sets corner 2 of the  arena
    usage: /<command>